### ISSUE TITLE
File path seems to be correct why is this happening

### ISSUE THREAD

**Issue by Venkat1abhinav** [souvikmajumder26/Land-Cover-Semantic-Segmentation-PyTorch#5]
`
Built the model successfully!
Traceback (most recent call last):
  File "/home/abhi/Land-Cover-Semantic-Segmentation-PyTorch-main/src/train.py", line 173, in <module>
    raise e
  File "/home/abhi/Land-Cover-Semantic-Segmentation-PyTorch-main/src/train.py", line 167, in <module>
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
  File "/home/abhi/.conda/envs/python-ml/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 351, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/home/abhi/.conda/envs/python-ml/lib/python3.9/site-packages/torch/utils/data/sampler.py", line 107, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0`

**Comment by Venkat1abhinav** [comment]
file path seems to be nice why is this still happening

**Comment by souvikmajumder26** [comment]
Check the last part of the error. The issue is not with the file path, it says that the value of "num_samples" should be a positive integer while it is zero in your case which is why the error.

**Comment by souvikmajumder26** [comment]
If you check the logs, there should be "Failed to initialize training and validation datasets and dataloaders!" at the last, which indicates there indeed is some issue with the train and test data path specifically.
The end part of the above error you pasted also denotes "num_samples=0" which means even if the data path is correct, there just might not be any images/files inside the train and test data folders.

Did you run this with your own dataset or the sample one I've provided in the repo as an example? If you're getting this error for your own dataset, can you please check once if it runs fine without making any changes to a freshly cloned project?

**Comment by Venkat1abhinav** [comment]
thanks turns out it was a small mistake by my parts but small question why is it talking more time to divide patches for me (7053/7053) patches for you it was just (144/144) why is that ?

**Comment by adityazarekar** [comment]
num_samples=0, Hi I am getting the same error, and used same repo, no changes done? where was the error @Venkat1abhinav


> ` Built the model successfully! Traceback (most recent call last): File "/home/abhi/Land-Cover-Semantic-Segmentation-PyTorch-main/src/train.py", line 173, in <module> raise e File "/home/abhi/Land-Cover-Semantic-Segmentation-PyTorch-main/src/train.py", line 167, in <module> train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True) File "/home/abhi/.conda/envs/python-ml/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 351, in __init__ sampler = RandomSampler(dataset, generator=generator) # type: ignore[arg-type] File "/home/abhi/.conda/envs/python-ml/lib/python3.9/site-packages/torch/utils/data/sampler.py", line 107, in __init__ raise ValueError("num_samples should be a positive integer " ValueError: num_samples should be a positive integer value, but got num_samples=0`

**Comment by adityazarekar** [comment]
Built the model successfully!
Traceback (most recent call last):
  File "C:\landcover\Land-Cover-Semantic-Segmentation-PyTorch\src\train.py", line 171, in <module>
    raise e
  File "C:\landcover\Land-Cover-Semantic-Segmentation-PyTorch\src\train.py", line 165, in <module>
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
  File "C:\ProgramData\anaconda3\envs\land\lib\site-packages\torch\utils\data\dataloader.py", line 351, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "C:\ProgramData\anaconda3\envs\land\lib\site-packages\torch\utils\data\sampler.py", line 107, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by souvikmajumder26** [comment]
Let's check a few things:

1. Have you kept images and masks in respective train folders with correct file extensions before running train.py?

2. Are you inside 'src' dir before executing "python train.py"? "python src/train.py" from project root folder may not work.

3. Please check or share the train log that should have been saved in the "logs" folder.

**Comment by Venkat1abhinav** [comment]
I don't really much remember how I fixed  but I will check the code in the morning (it's 1 am here) but if the remeber then you can get the data from landsat.ai( check the spelling from the Readme file ) download and data set split it using a split.py file (which I think was given or you can write based on how much you want to train) put the data in `data/train` and `data/test` it will work

**Comment by Venkat1abhinav** [comment]
Hi there! I'm not completely sure how I fixed it last time, but I'll review the code in the morning (it's 1 am here right now). In the meantime, if you recall, you can download the data from landsat.ai—please double-check the spelling in the README file. Once you've downloaded it, you can split the dataset using the provided split.py (or write your own version based on your training needs) and place the data into `data/train` and `data/test` modules That should do the trick. Thanks for your patience!
